name: Daily Reddit Data Collection

on:
  schedule:
    # Run hourly at minute 0 UTC (top of every hour)
    - cron: '0 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  collect-reddit-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install pinned runtime dependencies first so actions environments have everything needed
        pip install -r requirements.txt
        pip install -e .
      
    - name: Run Reddit data collection
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      run: python reddit_posts_collection_script.py
      
    - name: Upload artifacts (backup)
      uses: actions/upload-artifact@v4
      with:
        name: reddit-data-${{ github.run_number }}
        path: "*.csv"
        overwrite: true
        retention-days: 30
